local L = IGAS:NewLocale("Cube", "zhTW")
if not L then return end

L["Simple Dev Tool"] = "簡易開發工具"
L["Simple Debug Tool"] = "簡易調試工具"
L["Simple Bug List"] = "簡易錯誤清單"
L["Simple Log View"] = "簡易日誌監視"

L["Code"] = "程式"
L["Debug"] = "調試"
L["BugList"] = "錯誤"

L["Clear"] = "清除"
L["Clear All"] = "全部清除"
L["Enabled"] = "監測中"
L["Disabled"] = "已停用"

L["AutoRun"] = "自動運行"
L["New"] = "新設"
L["Save"] = "保存"
L["Del"] = "刪除"
L["Run"] = "運行"
L["Unit Test"] = "單元測試"
L["Must set code name."] = "保存用名稱沒有輸入。"
L["Must set code."] = "代碼沒有輸入。"
L["Load Addon"] = "載入插件"

L["Commit"] = "確定"
L["Show in new page"] = "顯示在另一頁"
L["Show metatable in new page"] = "將該項的MetaTable顯示在另一頁"
L["Show key in new page"] = "將鍵顯示在另一頁"
L["Delete this"] = "刪除此項"
L["Are you sure to delete this key?"] = "你確定要刪除這個鍵值嗎？"
L["Are you sure to change the value?"] = "你確定要修改這個值嗎？"
L["Error Input."] = "錯誤的輸入。"

L["Log View"] = "日誌監視"
L["Add Logger"] = "監視日誌"
L["Remove Logger"] = "移除日誌"
L["Clear Logger"] = "清空日誌"
L["Please input the logger's name"] = "請輸入要監視的日誌名稱"
L["Do you want remove the logger : "] = "請確認是否移除日誌:"
L["Do you want clear the logger : "] = "請確認是否清空日誌:"

L["Open the code editor"] = "打開簡易開發工具"
L["Open the buglist"] = "打開簡易錯誤清單"
L["Open the debug tool"] = "打開簡易調試工具"
L["Open the log view"] = "打開簡易日誌監視"

L["Log"] = "日誌"
L["Disable"] = "禁用"
L["Resume"] = "恢復"
L["Reset"] = "重置"

L["Show Row Number"] = "顯示行號"
L["Font Settings"] = "字體配置"
L["Path"] = "路徑"
L["Height"] = "高度"
L["Outline"] = "輪廓"
L["NONE"] = "無"
L["NORMAL"] = "普通"
L["THICK"] = "尖細"
L["Color Settings"] = "色彩配置"
L["Default Color"] = "默認色彩"
L["Comment Color"] = "注釋色彩"
L["String Color"] = "字符串色彩"
L["Number Color"] = "數字色彩"
L["Instruction Color"] = "關鍵字色彩"
L["Please input the font path"] = "請輸入字體文件所在路徑"
L["Please input the font height"] = "請輸入文字大小"

L["Do you want delete %s."] = "是否確認刪除%s"
L["Please input the snippet's name"] = "請輸入代碼段的名稱"
L["Please input the addon's name"] = "請輸入插件的名稱"
L["Please input the module's name"] = "請輸入模塊的名稱"
L["Can't save code."] = "無法保存"
L["Snippet is saved."] = "代碼段保存完畢"

L["Show Description"] = "顯示概要"